#!/bin/bash
export FILTER_BRANCH_SQUELCH_WARNING=1
for branch in $(git for-each-ref --format '%(refname:short)' refs/remotes/); do
  git checkout ${branch#origin/}
  git filter-branch -f --msg-filter 'sed "s/aider: //g"' --tag-name-filter cat -- --all
done
