#!/bin/bash
###
### Post-commit hook that decrypts files containing age encrypted kubernetes secrets
### File should be .git/hooks/post-commit and executable

# Add dependencies and includes
source includes/color.sh
source includes/depends.sh
source includes/encrypt-age.sh
source includes/keys.sh

export EXIT_STATUS=0

if [ ! -r '.k8s_password_hooks' ]; then
  export EXIT_STATUS=0
fi

# Ensure that age private key is configured
if [ $EXIT_STATUS = 0 ] ; then
  do_check_age_prv_key
fi

# Get list of files to decrypt, if they exist decrypt them
if [ $EXIT_STATUS = 0 ] ; then
  do_get_files_decrypt
  git add -A
fi
echo 
echo " Remove .vault_password_hooks from .gitgnore to prevent transparent decryption"
echo 
echo

exit $EXIT_STATUS