apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:L6vusqI7GmDhHgtmwRBegcjVdhhF/FBZBFnG0rQbYbRvV3HgOz2z3A==,iv:bfmjX/i9pJ/SSO15CG+KscGT23CBzBhXHLgEm9u/A/0=,tag:7zNrhaMkTbGh5m6uzf+z5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMTFQbXlnRW9icmhRL25V
            dUFjdU5xTC9hV3BscUJxdFlkTVhwTHVqRlVBCm9pT3ZFVVNMbjRZTHEwbWlOeXRX
            akdlakNjYmFzQVhnam55RlFuK0ZFQ1UKLS0tIEYySzA0YUo1dENPVjlTZldUU2xE
            bkYyTzNXODltcnpTQVBUc0hmMmlBN3MKWXFnQkP3mQWpcTUchy7KA+NR+hFI9L7A
            LfS2jzw9r7Bf+c0zMH7MACwOMzSKlRRkylFniuoE99lIAhoWf+ObNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:00:10Z"
    mac: ENC[AES256_GCM,data:AWWP98dkCxTba2Ov4x8pQHJFuOeTK2XykWjk4Xb66c5YiDQBQ+4Ta4/ZuYkISSouTm97UV3X419aKKM7LJwTgu6C/Q4a+qhKIawNHgy1l/f+jgEWcpWAZJKRGpc3Su8mLN2crc907wWdaCofr5tFCwG+hLCsy6re/BlJDqLowg8=,iv:g0b58vjyx7yK4eb8cXu+2yyH18n5O+NEKxK7m+ZZ07Q=,tag:pAE2O4R7xNUrMUlBc0XIRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:DY5WY6/ZjHpS5QgAN2xY42pTBWw=,iv:JlC6VJ5REyqxAF6c6FLOU/A2yZVX7z2GXdvYyDWbEq0=,tag:sy/gcNTU5wrZlIwap1ie4A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:e2whl4GQLJtKrZ4gE5u/NppsRfd70zO+D8p1LbGqeET1o0LgRSoLcQ==,iv:rPUJeEd1HG7cEgavhN0InWaSLt9L/IBgLtNDmxGRvnQ=,tag:9kpipZX4LyE9NkV2nN9ioQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMTFQbXlnRW9icmhRL25V
            dUFjdU5xTC9hV3BscUJxdFlkTVhwTHVqRlVBCm9pT3ZFVVNMbjRZTHEwbWlOeXRX
            akdlakNjYmFzQVhnam55RlFuK0ZFQ1UKLS0tIEYySzA0YUo1dENPVjlTZldUU2xE
            bkYyTzNXODltcnpTQVBUc0hmMmlBN3MKWXFnQkP3mQWpcTUchy7KA+NR+hFI9L7A
            LfS2jzw9r7Bf+c0zMH7MACwOMzSKlRRkylFniuoE99lIAhoWf+ObNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:00:10Z"
    mac: ENC[AES256_GCM,data:AWWP98dkCxTba2Ov4x8pQHJFuOeTK2XykWjk4Xb66c5YiDQBQ+4Ta4/ZuYkISSouTm97UV3X419aKKM7LJwTgu6C/Q4a+qhKIawNHgy1l/f+jgEWcpWAZJKRGpc3Su8mLN2crc907wWdaCofr5tFCwG+hLCsy6re/BlJDqLowg8=,iv:g0b58vjyx7yK4eb8cXu+2yyH18n5O+NEKxK7m+ZZ07Q=,tag:pAE2O4R7xNUrMUlBc0XIRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
