apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:vn9kv2g2mDtBzx4Nd25GdAjlx+ULK3ytqFw3iVj3L76vQaMscOxeZw==,iv:5U9AIJ3pBLe/KANX1b3FFI2e50RheJivdIbOzruWHyw=,tag:xxgrCq7hHwn4M+qIEO3zHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWalVtWFdFWUZvc293QkRT
            K3NCdlNkL1gvVjBuVWRDaE5PYkpmSWxraTNrClZPeklyYmFmQWNqazYxdGxSdzJz
            azlZbmxwUlM3ZGhqYzJDaUhlN0IxbG8KLS0tIEIrbGJyb0NZdVE1cldVL1d3OWs1
            ckFpYkpGNGJRdjlTaWhaK0Nhb1JsRG8KbqHC72mhFc0x2tOC8aeh7Xv31z5UlP8m
            Zu3SglEOjAmNlkGKyutgqx/4WKzjI4owyTVGAohq7AiEBI/xsVSU4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:04:39Z"
    mac: ENC[AES256_GCM,data:QB6Xfd0Z8tqkezuDx2RrcmKyPtkbDUrlRDN7eyQtmHNu5NydaXbIepsFzOKnm+ZaIB6Fwis4AgDppoyii5pgpj/r5rSTtbthmy+k71sNnqgM3y6CHanfbmGin0SYKh9ES5JAsoZ1G8RKnGifAR/+P7wasBlOP1uqtHIabcE13XQ=,iv:2Vm6HkvajJV7GU8ZnUp7ZJmLQbyy+HQBODaE9dKmn2g=,tag:Oc6sW0Qz1q3SUJpD6kZvCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Zu4f9kTyNORikZb+7Wl2Sq13vpc=,iv:1c0lXlgsweofsU8cppLN7kvz/Rw0jr2p6gADwKZguPw=,tag:9RJ1PKHyjRbcHX5BMa8lxA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:K0PX/PYlTEwfYopqOjflXi2n+6NEBL+hN7qULEkhWYeXwbZrZ6urWw==,iv:MH3vCIONqhllKodYQNHCfOTyHuUYHdGGTdd//PcXoCU=,tag:njZ+tLXkV0NssnPDM7bsqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWalVtWFdFWUZvc293QkRT
            K3NCdlNkL1gvVjBuVWRDaE5PYkpmSWxraTNrClZPeklyYmFmQWNqazYxdGxSdzJz
            azlZbmxwUlM3ZGhqYzJDaUhlN0IxbG8KLS0tIEIrbGJyb0NZdVE1cldVL1d3OWs1
            ckFpYkpGNGJRdjlTaWhaK0Nhb1JsRG8KbqHC72mhFc0x2tOC8aeh7Xv31z5UlP8m
            Zu3SglEOjAmNlkGKyutgqx/4WKzjI4owyTVGAohq7AiEBI/xsVSU4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:04:39Z"
    mac: ENC[AES256_GCM,data:QB6Xfd0Z8tqkezuDx2RrcmKyPtkbDUrlRDN7eyQtmHNu5NydaXbIepsFzOKnm+ZaIB6Fwis4AgDppoyii5pgpj/r5rSTtbthmy+k71sNnqgM3y6CHanfbmGin0SYKh9ES5JAsoZ1G8RKnGifAR/+P7wasBlOP1uqtHIabcE13XQ=,iv:2Vm6HkvajJV7GU8ZnUp7ZJmLQbyy+HQBODaE9dKmn2g=,tag:Oc6sW0Qz1q3SUJpD6kZvCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
