apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:gE6vCNsP6RV9SlAOq+rjhQJRFYaszefkWnj07ql92qdDfg/s6auCwg==,iv:9aNUVOPcG89bU/cOVfhLuvYcjyc2tofagMIphXTkrW0=,tag:fu1dW2wzI7g0a0FE9H5F4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNlIwdnViTHl6TTMzQnhN
            QWx4OUpRUXlZbDRLcWJEVFFnZ2Q5UTZlSTJJCjlhR2xxTzZrbWpZTFN6NmFzS2h5
            YjhNT2ViZW9xSFc1YnVoNmFzTkc0eWsKLS0tIDJBWHdaSEJSTElkMWtSL05lWCts
            dUxJRkNlL2RHdzNaQ0tZOVVtYnpQajgK7QzvmzxJa0+HJAw86qOi2MtziBlvbWQo
            /jTioPZK4SdfEvJZ91dy1ZqCv/QLLCZ9dUpf0qmpJuevvPVmwC1Mrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:04:13Z"
    mac: ENC[AES256_GCM,data:8WFYBMzstScG80Mowyoq0z3AcRTKq8WW+H7bnipmb5iAkxq7X1dvyyvuYs7Hv1QvTZ7L3SuLJutTw4PihuPzCDxxqxYs08j3IQdAUnO2ZKxKsJGW+EZqA0OtHIPOM8g5VsdKeVlx2D8D67ug7udKvernnUbfrntIb0YQ7/K5lks=,iv:zQH/SQCi1WP9n2RHcmMAMrhIjg3PqwxAC1sFgJ1d2ZQ=,tag:2cNpcwT64cJ5CTidojdZmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:gwMlBF8YTQUmz5JsE2vYFYnQYOE=,iv:IKJsfJmpgaaWJFj0W3Do99oOIgdkiIhG98JhKLAeIcE=,tag:UmAEQFMMqfBtzv2NRwb3zw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uAY1qzOMqnwUVPhlMu18r36Z7x2O89jLGI5kjrmUCpTonVNgZ9FCzw==,iv:UD3sfBg4SP6JEBOn/sy0efcm84jSsgASp6UMfCa7bZA=,tag:YpbxBG83Eb4KiOxAYn3PAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNlIwdnViTHl6TTMzQnhN
            QWx4OUpRUXlZbDRLcWJEVFFnZ2Q5UTZlSTJJCjlhR2xxTzZrbWpZTFN6NmFzS2h5
            YjhNT2ViZW9xSFc1YnVoNmFzTkc0eWsKLS0tIDJBWHdaSEJSTElkMWtSL05lWCts
            dUxJRkNlL2RHdzNaQ0tZOVVtYnpQajgK7QzvmzxJa0+HJAw86qOi2MtziBlvbWQo
            /jTioPZK4SdfEvJZ91dy1ZqCv/QLLCZ9dUpf0qmpJuevvPVmwC1Mrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:04:13Z"
    mac: ENC[AES256_GCM,data:8WFYBMzstScG80Mowyoq0z3AcRTKq8WW+H7bnipmb5iAkxq7X1dvyyvuYs7Hv1QvTZ7L3SuLJutTw4PihuPzCDxxqxYs08j3IQdAUnO2ZKxKsJGW+EZqA0OtHIPOM8g5VsdKeVlx2D8D67ug7udKvernnUbfrntIb0YQ7/K5lks=,iv:zQH/SQCi1WP9n2RHcmMAMrhIjg3PqwxAC1sFgJ1d2ZQ=,tag:2cNpcwT64cJ5CTidojdZmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
