apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:e/LNwJSKQfduWPHG33xTGHmu69NKT0hdlWmeSQfjimUIAdkWJTS3Gg==,iv:ckX3hol+pbqQDSr79GJZA0ULE4D52EMOapoIPdwjIL8=,tag:sN+dLcOhiOzN4LoO8tUKzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cDlxRGQySVZMbldabDBq
            Yi9XbGZrbDRwRkMwdUVTaFBlKzRGcXdhZnpjCkpCWDQ5QnA4MllSR3RsSG9BMXUy
            bmh1dXpnMWtzeGo1dy94THJ1N0UzOVUKLS0tIFdmSU0xaHZWcEpPbk43TEhGNWVP
            ZEVXUWZQaHNOTVUxNFhkaEZGTWZlQjgKLxoYRlYIbr9o6WllMF/gETKJlv5uPBoS
            BShCgWzMgeHNGIJ+AW7rIFfvCJkY+6XiWOmHXAwJoJ5BW6oxtTJZFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T03:52:36Z"
    mac: ENC[AES256_GCM,data:084dShboJd4re7uVJ3hfdG8YzUVM96ZBYhH2UKi4102n3CeRy0Dqr2yJoXhu8j5tYoafCwTfxBtmZjVaB5prx35eWhdsm6MPd88iYPYqir+j6kQJ5CgJ2+8EE8tTpvKxf+5d+sm0yenm8Si39SlrrCmHon0MOy/El3LHCWDgTH8=,iv:a9eSjYhUSQ/S03aNPAk5b9OURXNBx2pplfA2K5ph7+w=,tag:ZGQGTu+E3jPVrkqx53T7/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:rLGduCtJdF5YKAwUQptzPSE31WU=,iv:1pu+Xoc2PzBxpeM0DqTYZIRiTyJ8ot0OXRhLl79QeyA=,tag:fRu7+YxxXn35bB5gyHk3Iw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:EWsmCT7Tor/QpadzVqJ/gxkFQd57davTJ4QFUF36gDcyNijP0F7tog==,iv:6YwoTiNRYdBg7DMilE5OAhhLJlTws0orrncheE7tjdk=,tag:cctuVUaeUx/vXgm/uY8mrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cDlxRGQySVZMbldabDBq
            Yi9XbGZrbDRwRkMwdUVTaFBlKzRGcXdhZnpjCkpCWDQ5QnA4MllSR3RsSG9BMXUy
            bmh1dXpnMWtzeGo1dy94THJ1N0UzOVUKLS0tIFdmSU0xaHZWcEpPbk43TEhGNWVP
            ZEVXUWZQaHNOTVUxNFhkaEZGTWZlQjgKLxoYRlYIbr9o6WllMF/gETKJlv5uPBoS
            BShCgWzMgeHNGIJ+AW7rIFfvCJkY+6XiWOmHXAwJoJ5BW6oxtTJZFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T03:52:36Z"
    mac: ENC[AES256_GCM,data:084dShboJd4re7uVJ3hfdG8YzUVM96ZBYhH2UKi4102n3CeRy0Dqr2yJoXhu8j5tYoafCwTfxBtmZjVaB5prx35eWhdsm6MPd88iYPYqir+j6kQJ5CgJ2+8EE8tTpvKxf+5d+sm0yenm8Si39SlrrCmHon0MOy/El3LHCWDgTH8=,iv:a9eSjYhUSQ/S03aNPAk5b9OURXNBx2pplfA2K5ph7+w=,tag:ZGQGTu+E3jPVrkqx53T7/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
