apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:h1QB4NgPBUHUVHFimyKHhMD2GSP2HuYV+cclzdYoCUqGpcpBwjShYg==,iv:63BvFgcWJHxh4UMIed90SarC+Nv7MahdnZv2Qj6Wkvg=,tag:JUMEMYBe0J/yHRoZr9TvQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YVMzTkM3OUp0OG4vK0Fm
            SnZTd3BrTi85Qms1cU9FdnR2Tm05cmo3RG1JCkJYYm5BUmVKbXhZM0ttVnRLR1ps
            Y0VIVmd0SXBZM0ZLT0hpWWRKcThhdU0KLS0tIDZXOUt6T2hBZEoycmhQUXlhSXV5
            NHU2RFZRNlNWckZWTjJPUFZPWEI2YWsKM/JNdM1lM3gLCxE352ZGxsevq1nxwTWp
            Pu6r53e6wsCITjKYuHTdk71TZ/orZlbDC70bwWFj2MH+e9omL2W99Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:03:52Z"
    mac: ENC[AES256_GCM,data:aG7/6eof6G4uRNMXo+jkxNk4GGI9GEJId5QM25BiypI4HeBUkrDU+G8GY5A61wm+NtaeDbKUM2+olcQdnqfzjWonWtWTUddc6tLv+2AtdOfJgEjSVH3Bo6AgJ3a1j9YBHwBm/vbtDuIcQUM+0L5MSfVrs/e8EeJu8O6yg6yY4Pw=,iv:pgz1a3A3gSbMIfiUIbiaSl9kHvhrgBsEVHVkQnBwJsg=,tag:K5cu16KcSdWN5wYqg3/xjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VtFvrz7sYyXWByNRJxq5L9mlu+E=,iv:BGhU2BZz0j9uwAoPSsXmEnWYL/FG0Cetl9HKwUcH2aU=,tag:FhhMg4xU7DNUT/3HCXvX2Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:CHrSKMyb48bhjDS9inLFoqJZDCrCf38a8+2HRoftPbb1DK5+e2xJ/g==,iv:ZdJbybZQApGXGXdaq9sPPL/1dcTE3ebpfRGDBlWk1nc=,tag:1k4d4+FKrek0E1ShdrALKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YVMzTkM3OUp0OG4vK0Fm
            SnZTd3BrTi85Qms1cU9FdnR2Tm05cmo3RG1JCkJYYm5BUmVKbXhZM0ttVnRLR1ps
            Y0VIVmd0SXBZM0ZLT0hpWWRKcThhdU0KLS0tIDZXOUt6T2hBZEoycmhQUXlhSXV5
            NHU2RFZRNlNWckZWTjJPUFZPWEI2YWsKM/JNdM1lM3gLCxE352ZGxsevq1nxwTWp
            Pu6r53e6wsCITjKYuHTdk71TZ/orZlbDC70bwWFj2MH+e9omL2W99Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:03:52Z"
    mac: ENC[AES256_GCM,data:aG7/6eof6G4uRNMXo+jkxNk4GGI9GEJId5QM25BiypI4HeBUkrDU+G8GY5A61wm+NtaeDbKUM2+olcQdnqfzjWonWtWTUddc6tLv+2AtdOfJgEjSVH3Bo6AgJ3a1j9YBHwBm/vbtDuIcQUM+0L5MSfVrs/e8EeJu8O6yg6yY4Pw=,iv:pgz1a3A3gSbMIfiUIbiaSl9kHvhrgBsEVHVkQnBwJsg=,tag:K5cu16KcSdWN5wYqg3/xjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
