apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:Er/3hpc9tPZvOV1BYj6xn3LCoHcPp2llTFTGKqZQr5Xz1RY5nhb8eA==,iv:+f7mgEo8Bz9MSJwEk7j+kexQ0Udy7Imj+dGfQbUuP70=,tag:CQEx+IhN60xxTU5oGsPrHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbHdzUE9iWDV6bytCTU1q
            WndCZGNsSTBDYWJoN28yc0lWS0Y2S0VZbkZvCjZSYjdTNkJsVVJTYkova1Q1eW9D
            ZmZxclE0dzVBdUZZWUVYT3hudHk3YTQKLS0tIEFsUWc0T2Q2T0NSSm5kb3NzeGZS
            bFdIT0dhMTN5L0I3bDdOazFQV2c1OGMKTbkoHcNrgOfcHaOe6z+rtE/xiq4jFehR
            tyD6LzlsLq36uBYdNGF6VO8kdBB5EevS1wIOrlekRokjFjxXls/qSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:05:33Z"
    mac: ENC[AES256_GCM,data:x/nUQmXRvJShS2CXYHvR+SS91LH60fEGddUIw4rXpn1oOAIDws/lcCZIN2wt2PL1N2PPRuOB5iUaK3gwfQlaTlsOsTnNXY7Z/6zaG+/SCKm31ry49vkb5JFGuia34Q55IWmXXAEF4CMesyjSy/ekasw5cE6ehSQ5B0AVp7SIiac=,iv:Sjaa5ogWD0y04yDonaMMWNoHAF6kLLRHN0rQPCLhfF8=,tag:ERRJ67tvDnWuNGUkpjdKXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8mM7vw6U+eI/tJcpp476EnUr6Ws=,iv:TSsVEWrHdvEkgo8H4fO0M9zGWcuQlHtXfGgPHVXLYNc=,tag:+N4GCf53rVbJgIcAqim+2g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:E0b6SS3kaWrtK6Ist5OiLTRmeVYlggldNsbQZTM8JXamyfCrRjDqLQ==,iv:mQtnrpbGU3RlbORDim/xCDbpqYqDAF2tZToT7aXV9LA=,tag:JbRdRZEinHIv8nKO2zDTIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbHdzUE9iWDV6bytCTU1q
            WndCZGNsSTBDYWJoN28yc0lWS0Y2S0VZbkZvCjZSYjdTNkJsVVJTYkova1Q1eW9D
            ZmZxclE0dzVBdUZZWUVYT3hudHk3YTQKLS0tIEFsUWc0T2Q2T0NSSm5kb3NzeGZS
            bFdIT0dhMTN5L0I3bDdOazFQV2c1OGMKTbkoHcNrgOfcHaOe6z+rtE/xiq4jFehR
            tyD6LzlsLq36uBYdNGF6VO8kdBB5EevS1wIOrlekRokjFjxXls/qSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:05:33Z"
    mac: ENC[AES256_GCM,data:x/nUQmXRvJShS2CXYHvR+SS91LH60fEGddUIw4rXpn1oOAIDws/lcCZIN2wt2PL1N2PPRuOB5iUaK3gwfQlaTlsOsTnNXY7Z/6zaG+/SCKm31ry49vkb5JFGuia34Q55IWmXXAEF4CMesyjSy/ekasw5cE6ehSQ5B0AVp7SIiac=,iv:Sjaa5ogWD0y04yDonaMMWNoHAF6kLLRHN0rQPCLhfF8=,tag:ERRJ67tvDnWuNGUkpjdKXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
