apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:/G1bosofcPe4ydS8zMTMl8BkZhrFrtSY23CkowHyytweJD8Dk8g1JA==,iv:PSG4QdfRMTGMOumOxQbjlCwFB4YpmiCW7LIKUkihnGw=,tag:gsbMFPBEZdOKnWQ+C9TzEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cG9sNW9nV1FDYnBob1dY
            d0thMTBFWGF6YzVBM3g0NC9vcVpBRkZsbVZ3CkdSSUVJQ3YwU3lnNm0weGtUMURu
            cEZwaXVBUEVDZlY3ckpNZFhyQnFaaGsKLS0tIGJSMXVlbUhnREliaFVrUU5RVDM0
            U3ZjRHZQeDRLcmo4dFlzR3NmZ212LzAK7QatJc6AlhPyI0gCXoVmamEdToRAt2+g
            F0eF6N6T3xnCCk/8Z9LMfqs4lXdWI9peXFhMRC7gXvSHiY1iXg0oVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:18:05Z"
    mac: ENC[AES256_GCM,data:kYwT9+2920vdp6h8hOvIW5PdPrxoccEidOW9AAHEsdBfCB5eSSlYpLGs5DuKAGJk5V11sJWtS0cieRxxtJTOmCFL6U2g03thYtkGHQRyEPlKg1AKbdJbErImRfLno+x61bqKUqf3YJ/QNqrX9faUL56GW9QK37S1n6HZGoox+4M=,iv:nZp3CVhOhgS4io1IU7FMfWz7+BEKZu0d+tnO/YY9tBI=,tag:Wu+JMCo/0PPbGzkhCEt/WA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6S20tiwb1wx+ISX5fECyQ+shujs=,iv:jRmGYQlu9Yog9oyzUQZnUtl/a7Xu5BjBgsND5W8UHi0=,tag:Hgb7iL1+86FrSpX5TFel6Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RQcKYWqvBBqdguU4/Llc7UafzeNdmZY+jWiu7RrfN3HmWEaw/jNTyA==,iv:Qrpb7yYnBpSZPmPBEADmb1a+DpP2HX/8MN540wNfXK0=,tag:D3IQZPLngmptt/q/0Z0Tyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cG9sNW9nV1FDYnBob1dY
            d0thMTBFWGF6YzVBM3g0NC9vcVpBRkZsbVZ3CkdSSUVJQ3YwU3lnNm0weGtUMURu
            cEZwaXVBUEVDZlY3ckpNZFhyQnFaaGsKLS0tIGJSMXVlbUhnREliaFVrUU5RVDM0
            U3ZjRHZQeDRLcmo4dFlzR3NmZ212LzAK7QatJc6AlhPyI0gCXoVmamEdToRAt2+g
            F0eF6N6T3xnCCk/8Z9LMfqs4lXdWI9peXFhMRC7gXvSHiY1iXg0oVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:18:05Z"
    mac: ENC[AES256_GCM,data:kYwT9+2920vdp6h8hOvIW5PdPrxoccEidOW9AAHEsdBfCB5eSSlYpLGs5DuKAGJk5V11sJWtS0cieRxxtJTOmCFL6U2g03thYtkGHQRyEPlKg1AKbdJbErImRfLno+x61bqKUqf3YJ/QNqrX9faUL56GW9QK37S1n6HZGoox+4M=,iv:nZp3CVhOhgS4io1IU7FMfWz7+BEKZu0d+tnO/YY9tBI=,tag:Wu+JMCo/0PPbGzkhCEt/WA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
