apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:yp/pX5DBeyo4ajkkvXdmLn0ZEbIOVezEdPObgSxIR9qm8a2MvHeyQg==,iv:7eRWeP6uZE7MBwy7AbeUPh2zguEjYe2HKn3wBlN2m5Q=,tag:/EfiPdi5aGrKMO52+pAdSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSGR6UlJNQzBsMXhjZndQ
            VHozUlhuZExnL0RuWkJuMVFNUmtQbzRLNGlFClp5UHh2VVozVE9leWFSQXExT1NR
            OEN0dTg3SDBnek1oYi9hanJic3lockEKLS0tIHVva25Cc05vbkZsZTlJa2pVWVFH
            dkRXZEd2aXBHQ1dlR1pNZFlsODhDSVUKKXC8F++mE0VIDtncN28vL/sDalJqYwlo
            JUvGQux4rDqatGfYio45nBYuWMCrYzr8MDCwarDJ1i4aGEonvgBmrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:04:06Z"
    mac: ENC[AES256_GCM,data:mXLAWwQ8mNFSoo3ArXvAqEG399URC9nMuTGdeG0ix0nUKo5BI7R7F/6Z7P1TQDnZtAPonz7rJB0zYRtgyQmtA/MO/vR6vVTxcl+WhSSH/cF75oC8netDcg/JPdT6kJ0/X8bUdV8EuT+Y9xzu/wVWm9++wASGQDr/Sw3NqOqok5s=,iv:oowFvEzJuQeeK5jHOCZcw8z+/9ShaPYJO4zuM2+1mFA=,tag:7Lpj3D9+uVtmsJ0NeNTW3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:i8d7yOadFR9Fgs7nPijKOWE1L8o=,iv:R8/F3iW+KcqY3TuHQGubAccf8ZCARMJSgENE5viYjg8=,tag:7LgWRler45Hm6W5P7nl7Fg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:EqE1fyFoKqsCcxlXLrAh5IOr2fOl8+WSWoeJQcy2ZJxxmxFYv+g7Cg==,iv:e5V9kH3mYHrcQG0RN3xr71brWRAO6r2/UJ5zm59i9RU=,tag:3rON6wlJC737+fWJsTUqzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSGR6UlJNQzBsMXhjZndQ
            VHozUlhuZExnL0RuWkJuMVFNUmtQbzRLNGlFClp5UHh2VVozVE9leWFSQXExT1NR
            OEN0dTg3SDBnek1oYi9hanJic3lockEKLS0tIHVva25Cc05vbkZsZTlJa2pVWVFH
            dkRXZEd2aXBHQ1dlR1pNZFlsODhDSVUKKXC8F++mE0VIDtncN28vL/sDalJqYwlo
            JUvGQux4rDqatGfYio45nBYuWMCrYzr8MDCwarDJ1i4aGEonvgBmrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:04:06Z"
    mac: ENC[AES256_GCM,data:mXLAWwQ8mNFSoo3ArXvAqEG399URC9nMuTGdeG0ix0nUKo5BI7R7F/6Z7P1TQDnZtAPonz7rJB0zYRtgyQmtA/MO/vR6vVTxcl+WhSSH/cF75oC8netDcg/JPdT6kJ0/X8bUdV8EuT+Y9xzu/wVWm9++wASGQDr/Sw3NqOqok5s=,iv:oowFvEzJuQeeK5jHOCZcw8z+/9ShaPYJO4zuM2+1mFA=,tag:7Lpj3D9+uVtmsJ0NeNTW3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
