apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:S57Hwng+EfnCT9Yxbek7o2x+suqizr5duhHm+hJPkoDSQjle0jtZhQ==,iv:zmva0Yg/c98/n0sbeiMNX72FiMIuxrQarUTHj2Vs/V4=,tag:yFfyZcuWlrqHcHcUiW5WRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOEY3RTV5L3U2Yk5UTzY0
            K3dHUUhuRVJ6VWFpZ3lpcVBPaGZpYUdVRVdZClk5UzFiTHlseW9ORXA3NmhVS0FK
            a2psemMvVmMvcDhpZWNydmF1WUpvWDQKLS0tIEhIN3JTRmlqVVNpaUVPNS9VNWVj
            WVFsWTc4VmU3QnRwOEVpbEFFM3NXOHMKM/tbHxd3rYZ1tIrVGA1j5/36kHPvu16N
            DT98QfyckxTfAJLkf2+xYY2dpoFV4NLVwhv4bt8eptAfAkEmd8BLxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:04:07Z"
    mac: ENC[AES256_GCM,data:OgbNsDRylesX88uaNlAGBY4GJzCehhaU9U5qUUq8m52DHLrcnF8E1JHsxBm5j9SKrrFhkmvpnQCGTkF4EouKMY1cV7oJksaLWyUZCH8ldvTFjTuy8Rd2/Pm6V1oK0Ts2pw8VoCWge1P4/SScamgbYtO36ud2m7SmwZxetvO/ZVc=,iv:KiS3wifv4MMgEGKWClTCqeuhcw3Of973SXyXrbo1Ezo=,tag:0tafScmosjWv4brfj5IX7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3eBSjet/vK+RaY8MUP68xC4LfaE=,iv:Of1FDVnEqh2fW/r4Eaz8ymE/sr7tB0XTlBlCJi+X3Ok=,tag:tf9Fd+uVbqhiMScrcN/Maw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2igBavvkTpd1SzohcbZfj1WnD0ZXXfFcdloZog7vBya6ADH23CFnIQ==,iv:aCZ9Yv1tHtBTcxw+WGKr91zYLPICL0Y0Io+/pivwyD4=,tag:Sc10dcaY5TpigV6q76pa1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOEY3RTV5L3U2Yk5UTzY0
            K3dHUUhuRVJ6VWFpZ3lpcVBPaGZpYUdVRVdZClk5UzFiTHlseW9ORXA3NmhVS0FK
            a2psemMvVmMvcDhpZWNydmF1WUpvWDQKLS0tIEhIN3JTRmlqVVNpaUVPNS9VNWVj
            WVFsWTc4VmU3QnRwOEVpbEFFM3NXOHMKM/tbHxd3rYZ1tIrVGA1j5/36kHPvu16N
            DT98QfyckxTfAJLkf2+xYY2dpoFV4NLVwhv4bt8eptAfAkEmd8BLxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:04:07Z"
    mac: ENC[AES256_GCM,data:OgbNsDRylesX88uaNlAGBY4GJzCehhaU9U5qUUq8m52DHLrcnF8E1JHsxBm5j9SKrrFhkmvpnQCGTkF4EouKMY1cV7oJksaLWyUZCH8ldvTFjTuy8Rd2/Pm6V1oK0Ts2pw8VoCWge1P4/SScamgbYtO36ud2m7SmwZxetvO/ZVc=,iv:KiS3wifv4MMgEGKWClTCqeuhcw3Of973SXyXrbo1Ezo=,tag:0tafScmosjWv4brfj5IX7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
