apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:8bGLAIy319Z0YwAbtAZKjgKxHPfKUIS8cncxcvC+aaMXejuNPatuVw==,iv:PSL7YIps7IeRnXotd+zA8Zpk3mMnwLtW3JL3E3Xd0pI=,tag:OIYlAiq5zvH7T7BrRMy9Ow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMWdzcUZiVWczSDNhOEVL
            OStXQ3NCbGxuVUlyZW1YdnJscXAxTzhTMFV3CmZrT0dhY08yc0lkZ1RlYUxpYnB2
            SFhpL2tBTXFWZ0N5dlFidC9hSFhOcGcKLS0tIGwvd3MzdFMrVHRnSlg0cEtzVCtn
            SUpPK3BCbnluTlArTW5hekM0dWp4Z1kKTNkXTksfwPgbz4BLsG05fYas6nb0mkCZ
            ZIroKjTQUz9aITiNFSwzAnhxL2Vr3WNcFNMT5epOSuaZz8N8y8wZNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:00:03Z"
    mac: ENC[AES256_GCM,data:N+K/JuERDCVbaWzjLxYzteTYI/5iFDgl2wAgOIuhwRs4mxHpjrAjQoBGyKO26VTCK01EA3c8iANt3OXUeoYwd5YIp1/t9cQaIU3rBQczCDZebcdiFWTWwo4fZf6jJNTAPHnlYiO4NyBBybhOxPPnlhTREdJ1IKgKKN872KT5f24=,iv:sLfSY1axTkYSgGL0BWNNEaoLYVb0eN6wsvx75JrL7CQ=,tag:P1Ja7D3c1i+5VNssjBX1ow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:nTGDEqsIh2SnzpkBfqOmb9mqcEM=,iv:J1V/3BqHkztZIO0NhYRNe4FsZww/mbj+DErJMPQBEEE=,tag:pXt9krM5pfGXdFY1eO2Erg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:08w+an/KLu0l/rfGV8DyezDr6Sd4h/sN9dA79LlA9cAyRulVeUOwgQ==,iv:2BgehBD+n7GTsR8hBMh7h9ZOIPVTBmPtue2KS/uWXuI=,tag:Iwu5UmLWSYhn0GqwVdHwDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMWdzcUZiVWczSDNhOEVL
            OStXQ3NCbGxuVUlyZW1YdnJscXAxTzhTMFV3CmZrT0dhY08yc0lkZ1RlYUxpYnB2
            SFhpL2tBTXFWZ0N5dlFidC9hSFhOcGcKLS0tIGwvd3MzdFMrVHRnSlg0cEtzVCtn
            SUpPK3BCbnluTlArTW5hekM0dWp4Z1kKTNkXTksfwPgbz4BLsG05fYas6nb0mkCZ
            ZIroKjTQUz9aITiNFSwzAnhxL2Vr3WNcFNMT5epOSuaZz8N8y8wZNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:00:03Z"
    mac: ENC[AES256_GCM,data:N+K/JuERDCVbaWzjLxYzteTYI/5iFDgl2wAgOIuhwRs4mxHpjrAjQoBGyKO26VTCK01EA3c8iANt3OXUeoYwd5YIp1/t9cQaIU3rBQczCDZebcdiFWTWwo4fZf6jJNTAPHnlYiO4NyBBybhOxPPnlhTREdJ1IKgKKN872KT5f24=,iv:sLfSY1axTkYSgGL0BWNNEaoLYVb0eN6wsvx75JrL7CQ=,tag:P1Ja7D3c1i+5VNssjBX1ow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
