apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:nc9vA3lqVw13msqYbh/y0tzVzb0yPYQWHGZ5ztyRF4JmnGxZ32TZIA==,iv:A2rnMBtITT7ZEMh2t5lBfa0f6rE0vSFC3RJbyvdB71s=,tag:0XsMIe8OShHOcz/tANQJ8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVjREbk9lREdlRmJybi8r
            UU4yWjhLOWIyNTFIZzdwVFZMcUdQd2Q1YnhVCnlTTUdvb3VuL2NPa3UzODR6VXMv
            QVJsWGdEUUtOQVNKemlPa0J3MnVRd00KLS0tIDFDS2swczd1Y2FEMzFadkswd1do
            RjdkM3cwTDNJRTJjdVQ4aTc1d0E0WjgKvtmpHBl2FCisZyNSgo1rTZyfFu7HBrbo
            jOHmeG73FJ0RZQqDf0mHtby9wwECcGlWF2LNFK0oX0eodvM2kWB7ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:18:06Z"
    mac: ENC[AES256_GCM,data:4J+riScLqYBEQB5ecrCHY2yIHjR31HAljTbpVEwrDazxJUK2200RYlUilH+lpFSCJs+8fNNrUTO8Vq6k2I0VWbEhfKuEXp6L4VM9amdgvaCO2wdntRDw7sam+kAK8f1PmiKYy7rbQwP5QZIA4gRtHf8HLBFAdFW6B3Nw59Prgmw=,iv:FQiHQDGb+dnPKxk4HR30KqJsLPDBvYEPNDhj1SU28mw=,tag:CW5cIjpi3J6KLqRZxfGirg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:HUe0kjmYhff7SjHhYAyiW3BzI4U=,iv:/ZwAFVG8n2R5OCZrpfAmFmYJ/+T69IVIhlKsbXiUMYs=,tag:n82M59Dg4JZ2fPFNOOY6nw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Gkp/4W0NEtOggm7jMPOkdWZXnIuwphoHgMZjL3M6D3SBEBuoXsTArQ==,iv:EC7zaLlFYukpu8bEfRhF6wy9Pn/ZQxzKTCEdTElBj6I=,tag:WDkkgv7JZAzAsrsLzfKUlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVjREbk9lREdlRmJybi8r
            UU4yWjhLOWIyNTFIZzdwVFZMcUdQd2Q1YnhVCnlTTUdvb3VuL2NPa3UzODR6VXMv
            QVJsWGdEUUtOQVNKemlPa0J3MnVRd00KLS0tIDFDS2swczd1Y2FEMzFadkswd1do
            RjdkM3cwTDNJRTJjdVQ4aTc1d0E0WjgKvtmpHBl2FCisZyNSgo1rTZyfFu7HBrbo
            jOHmeG73FJ0RZQqDf0mHtby9wwECcGlWF2LNFK0oX0eodvM2kWB7ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:18:06Z"
    mac: ENC[AES256_GCM,data:4J+riScLqYBEQB5ecrCHY2yIHjR31HAljTbpVEwrDazxJUK2200RYlUilH+lpFSCJs+8fNNrUTO8Vq6k2I0VWbEhfKuEXp6L4VM9amdgvaCO2wdntRDw7sam+kAK8f1PmiKYy7rbQwP5QZIA4gRtHf8HLBFAdFW6B3Nw59Prgmw=,iv:FQiHQDGb+dnPKxk4HR30KqJsLPDBvYEPNDhj1SU28mw=,tag:CW5cIjpi3J6KLqRZxfGirg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
