apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:DdGqB5sH7NvsJ657aXejoBuZUxOAJl1M7oWYWxlf4umxjLiPbu4dPg==,iv:954xsdsoOUKPFp1bT98rJKoaQx7AUKQ/2O+dfxvDEfo=,tag:MObEEcyd2Iykp+f+py9spA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdjFnQW1TVGFLR0praytR
            QzBEM3BHd0VEemN3ZkR3N2VMcmV1cE1XQUFnCjBYV3lvQ0RPelNOWnBxSUpNOGxU
            V2VLMDBmbzI1T05ReHBNaXdLUjZiTkEKLS0tIFFiRDArdkh2RURyRWdEYVhoWDRB
            MmpyOUFiaGszYmJlTGxTTksrZGZ4YmMKP364OxUwMAK8ri+EmUxTCSsg2nqmNxOS
            3aH3bNQQp0chDamXsLXokE9ZNPrJ8kiWKXRjQ06FKWrGWhz4n9nUMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:00:06Z"
    mac: ENC[AES256_GCM,data:uZXV8D0QMNJkiH+6Iqxid7I5u499skw85CB7KZSH2luF0hI8BjAMTLAOMy/03coyNG/ybuSlWjz6k49lH5M1oOOGFS1XI0J7xir2MofvIKUPwK917zsS/iBL0G5HwCP5p0TUhM5GGjU1CXjUZcTj/UY/V3A8CR1C3YJLEw4OPKs=,iv:PhLDZKP7qWfh3l0mlIFFHj9SKaYPhkn1nnF6hMQUtNw=,tag:ZxSEyop+0Q5mNz3QZECSuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:h3ZIJMeJUK1FChRm5x7/Ix+o9A4=,iv:VrBhvCERPFPHcQ56yYDLK5qilQN87bEWXmfuLv76j30=,tag:rBUmbyjRDvjgB3P0HRMEqA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JSbCFq+hgD16xSDddmYw5xAJb+CVI8tPi0iKYTEPhm8ZdAyjM2FtTw==,iv:18kOih/qPFcl4AQ+29JHKrEpc3DhzMkSqaKxDFakI1Y=,tag:eUsC81+B+1j3pX0kwCasRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdjFnQW1TVGFLR0praytR
            QzBEM3BHd0VEemN3ZkR3N2VMcmV1cE1XQUFnCjBYV3lvQ0RPelNOWnBxSUpNOGxU
            V2VLMDBmbzI1T05ReHBNaXdLUjZiTkEKLS0tIFFiRDArdkh2RURyRWdEYVhoWDRB
            MmpyOUFiaGszYmJlTGxTTksrZGZ4YmMKP364OxUwMAK8ri+EmUxTCSsg2nqmNxOS
            3aH3bNQQp0chDamXsLXokE9ZNPrJ8kiWKXRjQ06FKWrGWhz4n9nUMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:00:06Z"
    mac: ENC[AES256_GCM,data:uZXV8D0QMNJkiH+6Iqxid7I5u499skw85CB7KZSH2luF0hI8BjAMTLAOMy/03coyNG/ybuSlWjz6k49lH5M1oOOGFS1XI0J7xir2MofvIKUPwK917zsS/iBL0G5HwCP5p0TUhM5GGjU1CXjUZcTj/UY/V3A8CR1C3YJLEw4OPKs=,iv:PhLDZKP7qWfh3l0mlIFFHj9SKaYPhkn1nnF6hMQUtNw=,tag:ZxSEyop+0Q5mNz3QZECSuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
