apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:+NHMWee7ySCrOzcS40htb8Lo/GIcYhaFxA67tRT1yuHvloFbfHDS7w==,iv:mZpW6+hIslrbWdcOF0PRhrPGRhMrA/saN1tTFxuW6ts=,tag:n2D4j6lbOLdkxEDolMc8Bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WkNHQTk5T1ZBS21yWGZZ
            M2tTTXk3UWRHY2FvYnFVekk2VWNVeHJIL204CkRQVFZPT1RFbE1lZ1hzU0lpQlVr
            YjVEVTJOUHM5L3RKZElabzVTZFo5TEUKLS0tIE1rL0t4TC9SR04yZDZreFdCRURt
            TlFsRFF5anVCZXVQaXF6cWNnbWlQcEEK8t+x8sPRhgqWaaRfELdYDlph1mGBJ+aE
            PmjuwruqqTeYXCpRYi074X+BTT9nYTbdvGPiJYrNkOZW9d/E/rNNdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:03:55Z"
    mac: ENC[AES256_GCM,data:rwracW6/sozD0QcjGZdPFFTl5A3vgZcSklwzPS190ClshCquNUv1SMu6tJQpMfhCrEgB7tIwwj7t5E8BDWgginrf5sPTGd+Dznwmw0yl2CBgF25Hif4q6bJZ9BJgA13pwxBs4xhGwCLDiZ2XRP9ngAeKJFYufLPXC+h47dWaRWQ=,iv:M/s5ux8T7am9Dn31z4moJKLdFsm56V3ZF18/CWDmAGk=,tag:RThyRrpnDy5K/GqeQf8jxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3mIcadUh6kGfGahwa5MwVjyjX48=,iv:Lfeko9i6OBmAcpdCzzOCYv8DMt0Z9ksm5jjbRzSidCQ=,tag:Wp4oD4iQjXegJLYt67W0Yw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:UOGLIGhljETLQicgS9DyFS3j1r/HMBljl9oatC4Yff3NWTzvb/1x2w==,iv:mMcVXvl5P1668zGYoKXbJ2grM6oLbqAmv7dRqmY1uEk=,tag:xMubtJ7zLTrd4cvEo6rfDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WkNHQTk5T1ZBS21yWGZZ
            M2tTTXk3UWRHY2FvYnFVekk2VWNVeHJIL204CkRQVFZPT1RFbE1lZ1hzU0lpQlVr
            YjVEVTJOUHM5L3RKZElabzVTZFo5TEUKLS0tIE1rL0t4TC9SR04yZDZreFdCRURt
            TlFsRFF5anVCZXVQaXF6cWNnbWlQcEEK8t+x8sPRhgqWaaRfELdYDlph1mGBJ+aE
            PmjuwruqqTeYXCpRYi074X+BTT9nYTbdvGPiJYrNkOZW9d/E/rNNdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:03:55Z"
    mac: ENC[AES256_GCM,data:rwracW6/sozD0QcjGZdPFFTl5A3vgZcSklwzPS190ClshCquNUv1SMu6tJQpMfhCrEgB7tIwwj7t5E8BDWgginrf5sPTGd+Dznwmw0yl2CBgF25Hif4q6bJZ9BJgA13pwxBs4xhGwCLDiZ2XRP9ngAeKJFYufLPXC+h47dWaRWQ=,iv:M/s5ux8T7am9Dn31z4moJKLdFsm56V3ZF18/CWDmAGk=,tag:RThyRrpnDy5K/GqeQf8jxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
