apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:gaTaTvmd1Zrwh6FG2oole96dmC87FvHeBlKqMuut8IxM8rOhxEAmhg==,iv:xPAar6jPV0NcfifIh9ckdyHI4gUrgWC6zFzHolWRly4=,tag:ayfh6l7k8wTxUC8iv5yCLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibVBVRjdBYVJub2xpVW5q
            bFRnQmNnVXIyUnM1TUZ6UFNnTzNXRU5VazBvCkFsWFJUeWNiUnJsRDd1TDFxM2ZK
            SlA1ZEdhTkpHV09SQ2NXcHU4VENQbk0KLS0tIFZFTXpab0FQMEdVOFRoREFSR05q
            bVMyZGhRTmtGU0lQSlVYMHl3UisvbmcK8hRTw3pGzXae/s554lxn5q/yZ8MAE2yo
            uCjPZo1DFxQBk9JHqFk3GVG+8NQTQvIQS80ISwDtheIYmLvOLDRUzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:03:50Z"
    mac: ENC[AES256_GCM,data:vcwxei3giBU4kmLdCsYBH4ZVIP8aW23hq7iaG3k9hKDyAETjTUORySLzsZlUgQM3Hst6Fx6AMOKgEx1Cxst/8Qo7hUqCXvYk6hS6Aa29Z2s/RYxU9Q6FevPzS3W1UrdUlRMNnfRBCki2hQcwqKTaA48IaQf2z7aOrxW/JnJlTQI=,iv:5THgZh4ZnFiDqFaH5tFe4tpyPy/YauKNcdSoEuFcuCM=,tag:LYSwnRQJaTx8ext7CJKooQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Cri7uDsc9yKPZ4EhsFHsSJDoQmo=,iv:qaiXjekEAbpiVQy6nRllQ11C+FJ1mNcGeyKAxRSG0BA=,tag:em0KsKll5SI1oCW1Y33pvA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Zvy7gq+E2zVS7NqpvuCkNna0tcv7FGC2CKK2fhvO9zzM/9mPGauHZQ==,iv:WC7NdQSFRgJcpd3XmRJKK1xv8oeNsEqe3H7ysqE/jWM=,tag:bNOFd+Fg2KkcSe1XQCsylw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibVBVRjdBYVJub2xpVW5q
            bFRnQmNnVXIyUnM1TUZ6UFNnTzNXRU5VazBvCkFsWFJUeWNiUnJsRDd1TDFxM2ZK
            SlA1ZEdhTkpHV09SQ2NXcHU4VENQbk0KLS0tIFZFTXpab0FQMEdVOFRoREFSR05q
            bVMyZGhRTmtGU0lQSlVYMHl3UisvbmcK8hRTw3pGzXae/s554lxn5q/yZ8MAE2yo
            uCjPZo1DFxQBk9JHqFk3GVG+8NQTQvIQS80ISwDtheIYmLvOLDRUzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:03:50Z"
    mac: ENC[AES256_GCM,data:vcwxei3giBU4kmLdCsYBH4ZVIP8aW23hq7iaG3k9hKDyAETjTUORySLzsZlUgQM3Hst6Fx6AMOKgEx1Cxst/8Qo7hUqCXvYk6hS6Aa29Z2s/RYxU9Q6FevPzS3W1UrdUlRMNnfRBCki2hQcwqKTaA48IaQf2z7aOrxW/JnJlTQI=,iv:5THgZh4ZnFiDqFaH5tFe4tpyPy/YauKNcdSoEuFcuCM=,tag:LYSwnRQJaTx8ext7CJKooQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
