apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:tgPhgXYzjTKKgD9nXfFHNI3+kj0AzxVZa9+HRvM/NUPiU2h2h1x2UQ==,iv:5qC8RBCFx62JJQOz4q3jyhSg9gAyXIoPjTnydbrAkl0=,tag:7BKVBK5i3mZ8HxjAUy+pOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QU91MlJuN3F4QWR2bGFx
            VjEzVWRCMStDaVg2c0tqZU9uM0VhdEVNeVRRCmdmaG9kdWJTZWs4Umg3eWZkSEdm
            clFoNXZPK3dlMG15TWZZakg4V3hlUEkKLS0tIFFsRGRSMG0yTFRiQlRQNllsdDF6
            YjJGd21RaVNGNmljV004TGdjeHMyUG8KJXED0mRwNVA+0Q4VMEjzRSH0gTRZKOQC
            lYLhvMTZsKayrP99RfRXk8CvIGOQxsOcrqLzw243PFPVV5oB4n42aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:03:12Z"
    mac: ENC[AES256_GCM,data:6hCztx+tYacC8UURSTfOBlIbYgqU0xEguJFORi4PP6BsEqhRt8keJZw6F9l7UObGrS6PTc3kNrMndYnFI3NpIDHsaIUMXZ4KXejT4W6IYnI3Spsa4dpkwBc2xTinUNKhJOMgEb+9gZ+IeARF2inN+nAFjADFaT6c9hQhbxAxhNM=,iv:6rr/J2XRyfCgYVn4aBqhamgskkuRs3WeBLdwNFZBjDU=,tag:uFf02BStpKaETyZQ5qm5+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:o4kDZ/f4j51aOTDEcqseU/wJwi0=,iv:2sEhLDgm0ue8eM/Owe90ObMBefC1yD3Jgn8XXC58pG0=,tag:gJaPhvcWzMSWwxbwpn7G6A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JcHO4wNbhMtUHgEDuO2AsD9yr/QmI0r8+e0Q5xZx9UPzwsoXrV+9mA==,iv:A03wzH/IBocY5SuMq0Ny6cgFyGfMAlyYsM3dh/cvshs=,tag:ogCCClubbXdpWRrMdGZXdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QU91MlJuN3F4QWR2bGFx
            VjEzVWRCMStDaVg2c0tqZU9uM0VhdEVNeVRRCmdmaG9kdWJTZWs4Umg3eWZkSEdm
            clFoNXZPK3dlMG15TWZZakg4V3hlUEkKLS0tIFFsRGRSMG0yTFRiQlRQNllsdDF6
            YjJGd21RaVNGNmljV004TGdjeHMyUG8KJXED0mRwNVA+0Q4VMEjzRSH0gTRZKOQC
            lYLhvMTZsKayrP99RfRXk8CvIGOQxsOcrqLzw243PFPVV5oB4n42aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:03:12Z"
    mac: ENC[AES256_GCM,data:6hCztx+tYacC8UURSTfOBlIbYgqU0xEguJFORi4PP6BsEqhRt8keJZw6F9l7UObGrS6PTc3kNrMndYnFI3NpIDHsaIUMXZ4KXejT4W6IYnI3Spsa4dpkwBc2xTinUNKhJOMgEb+9gZ+IeARF2inN+nAFjADFaT6c9hQhbxAxhNM=,iv:6rr/J2XRyfCgYVn4aBqhamgskkuRs3WeBLdwNFZBjDU=,tag:uFf02BStpKaETyZQ5qm5+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
