apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:kUphB2qRdxs2MZww7FZ9YkvYysZ+lZK6jRRKxjXJVLcsEF+vroGkYQ==,iv:FLfDy4PzYFD6lLKoeMD4r/QiKs7qBHviFYLCSIUPla8=,tag:HgQ+rE9zufDuiJGWlWlz1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSm9MbzduUE1VUHZRK1pE
            aEM1RWszc2FWeXluNms5UW5mVnROa1krUFVVClV5WlRjTzNaSStwdDQrZk1peUt1
            THNvV1FCSjNuNVVUemxhd0pGTHVHVUEKLS0tIFhaeG94ekVOUVJoMW1hMkszQ25u
            NWlFUUFnUFdQaFFIWFRmMU55TERjeE0KBNBO4zjvZIx+LM2Mmw1EC9EXhCrDS7vP
            VUaUhr0i3Ywi6Eiq0Ao+3ku+Z3m1shJRKVoCBV5Pl9AHsFfRuqTTyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:19:52Z"
    mac: ENC[AES256_GCM,data:u1V0SY5JadKZhMpwmE4M4kJIQK9elF5ywg9O+04482YLSc81hySqwB9VEIJ3HBs5POyq48f21Ib8wtsDDTmYEkcfvH2AE9yMKpJKFtXqVCzSXWqVtlFyFhAcr548LVIA11/2iwKlI51iZOtyDIXM82NSbDteFAhNJHfZjXBLQn8=,iv:gzI/htPC2o3/rqU+uAYScW9w3VKLvkejujzaiMtvthc=,tag:1nFfD7arBGGX8yZWVgJ/jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:PpbZm5sGmt9m5rmSuxl7+YLE3Yc=,iv:rGGX3A2SLwFHEbA6esOcvyI0r8uzphtJTShf5adG/JY=,tag:8hx91yd9Mi/2FUkXmtK6Rg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:grC1UxEx5J7fuRmzSRSolU7IljolYifWZr53M9onSJroeo8qEP3plw==,iv:c3Q1QApxTF0Bui5W1di5GyxD5VBxdBlBcPcEI/Luu2M=,tag:7rdG9HhzmchS7EUi5FPwQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSm9MbzduUE1VUHZRK1pE
            aEM1RWszc2FWeXluNms5UW5mVnROa1krUFVVClV5WlRjTzNaSStwdDQrZk1peUt1
            THNvV1FCSjNuNVVUemxhd0pGTHVHVUEKLS0tIFhaeG94ekVOUVJoMW1hMkszQ25u
            NWlFUUFnUFdQaFFIWFRmMU55TERjeE0KBNBO4zjvZIx+LM2Mmw1EC9EXhCrDS7vP
            VUaUhr0i3Ywi6Eiq0Ao+3ku+Z3m1shJRKVoCBV5Pl9AHsFfRuqTTyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:19:52Z"
    mac: ENC[AES256_GCM,data:u1V0SY5JadKZhMpwmE4M4kJIQK9elF5ywg9O+04482YLSc81hySqwB9VEIJ3HBs5POyq48f21Ib8wtsDDTmYEkcfvH2AE9yMKpJKFtXqVCzSXWqVtlFyFhAcr548LVIA11/2iwKlI51iZOtyDIXM82NSbDteFAhNJHfZjXBLQn8=,iv:gzI/htPC2o3/rqU+uAYScW9w3VKLvkejujzaiMtvthc=,tag:1nFfD7arBGGX8yZWVgJ/jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
