apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:WtbGMrL71Xp2YfLnIiZfxzxKy6lMEaLbCGbXmZFfoZjhBwqEey2KBA==,iv:vcXx3nmUu+b0WOtoWLdSmzlFKWPLEbc4JE2CFRBDqYU=,tag:GeBsfi4evxJ2b9s9r6AmTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRGoyU3o5RzZoOWVqbFky
            UWFyY1lZazIxZnZzUDNjSHBocnRsN2RjYVNVClVCM0ltSm5VM0VrWVNEYWwzQ3Iv
            YlVBbTFTMlpiSXgwRThiaHFlaHVIeU0KLS0tIGxOcEF5eFU2c09oTkx6cm1td0tt
            UHdSQWxCaVBMall0OW13aG9JL2hkZWcK4J6lPqP04doLxu2dlqMlnkSk0IbVy0mV
            7OomXTt4DurUFpFKZRvAG0I/G9V8Pgu/eUgTQNHFdqWyPO5gLJjLpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T03:55:40Z"
    mac: ENC[AES256_GCM,data:30lfbVGzNKxzSSLkJN5uzcRsf8tm6qvQPnqNeDyG7R7Pcdbd8lZFPT5ZO68+5D988TNXWwlxZ+SRVor1nEjbt1DXZpZ6pe7pZRxqJM82oY2w8bwNGpzwY/Isn1uTcrJWyB5n4Gc7u3egjxJjst09SFKfs3T0gXA1kg0eReYI6ig=,iv:F3qSQ1HlbTu1SnZAKn6zzca/Jl5x84TGTmp+0ItyQR0=,tag:R9qf2YLQvemgtE1t3f44sQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:h/Hzpok070c2lxvIdozrqrMREPI=,iv:12AWM6SZG+b3IVX0XCxHmoGQ0ACsQmh4dO1Bm8gNLbA=,tag:dacyA6ye3/Iaa1AZT5yaUg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fWASlp0nN31lL2swlbeHrM+9UPjg4zp39wDM4dhZ3Ab42y5kwpWQ+w==,iv:e4q0Dd8xFVQSt9v8iojcjiovnrDQ0WNqExrreopN5aQ=,tag:xc9OPK7fq58azvZsaAFcyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRGoyU3o5RzZoOWVqbFky
            UWFyY1lZazIxZnZzUDNjSHBocnRsN2RjYVNVClVCM0ltSm5VM0VrWVNEYWwzQ3Iv
            YlVBbTFTMlpiSXgwRThiaHFlaHVIeU0KLS0tIGxOcEF5eFU2c09oTkx6cm1td0tt
            UHdSQWxCaVBMall0OW13aG9JL2hkZWcK4J6lPqP04doLxu2dlqMlnkSk0IbVy0mV
            7OomXTt4DurUFpFKZRvAG0I/G9V8Pgu/eUgTQNHFdqWyPO5gLJjLpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T03:55:40Z"
    mac: ENC[AES256_GCM,data:30lfbVGzNKxzSSLkJN5uzcRsf8tm6qvQPnqNeDyG7R7Pcdbd8lZFPT5ZO68+5D988TNXWwlxZ+SRVor1nEjbt1DXZpZ6pe7pZRxqJM82oY2w8bwNGpzwY/Isn1uTcrJWyB5n4Gc7u3egjxJjst09SFKfs3T0gXA1kg0eReYI6ig=,iv:F3qSQ1HlbTu1SnZAKn6zzca/Jl5x84TGTmp+0ItyQR0=,tag:R9qf2YLQvemgtE1t3f44sQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
