apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:y70EFKygeI8RZLdzNS4xEJHRtiqb5XDmNttlD2awW9luYnLwhk9jUw==,iv:/eAFMKjjpyXk0DfNp1BvIZq1xwzRFFgp4TfcBmSSJWU=,tag:w9s/ULit9Jygv8JVhw5cXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaDhhY3FwYm5lWnlwVi9R
            NldVQmdEcGx6WStWRXU1aGo0K2VrV0FFSFVVCkFSSm1iQ21wTWZYbHU3bW9EdUF4
            UWh3RzliOW14aHZZa1ZnYVFRTnBWRjQKLS0tIGNWU0J1MldiNzB3U1ZRcWVUb0s1
            TkRNNWNkbDlMeDVERTV2MlJ1K1ppRUUKQDDjmN8ARbuUZsaDCgM3+9pyB2c5KsTo
            I4OPnGXgu0WiCr9G4nWkiNRX6YI7TsqbzNoDejLCP/DQFeNzr1VHJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:03:10Z"
    mac: ENC[AES256_GCM,data:5MGxvCOvseSorzp/otb70EsZxiVlZh0KNMYIzhSGHkItPEDaYqdGBCgDcCO9zjNzRdRwLbq4xO7dYmB6XvADvLuuyA9Tw4cKkTneu59GLL5Z5YjnDBJ9BKGEcE7kdpocEgKFB+G9BfDxlqtEWnMUAUtHdvYVZNQxt+gqTEDIWz8=,iv:OWOlArzu1X5NPxlwSWJlizBo5O/nP898OuGiazxc3+s=,tag:AGPnoc831IFrhylhhr/94w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Ifya4kq3QcgU8NgRgirGXDDhF4U=,iv:qQE/z58x6Oe24/4TxmO6V0WOJBP6yaJVYAxA8tgyUBU=,tag:CPS9Jq6dI9ebd7dwFx9xUw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lIEns8zm7fvdeK6Xe31CK4D70PVG1HuoKPXiNiWD8Ls0+l3zCnevpA==,iv:Ofa1QQ4mADAjxnjMZp/ucz7P/x7EzegkBwbLq0tgWOI=,tag:AuSpVRnb4U0GELs9Q8JcXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaDhhY3FwYm5lWnlwVi9R
            NldVQmdEcGx6WStWRXU1aGo0K2VrV0FFSFVVCkFSSm1iQ21wTWZYbHU3bW9EdUF4
            UWh3RzliOW14aHZZa1ZnYVFRTnBWRjQKLS0tIGNWU0J1MldiNzB3U1ZRcWVUb0s1
            TkRNNWNkbDlMeDVERTV2MlJ1K1ppRUUKQDDjmN8ARbuUZsaDCgM3+9pyB2c5KsTo
            I4OPnGXgu0WiCr9G4nWkiNRX6YI7TsqbzNoDejLCP/DQFeNzr1VHJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:03:10Z"
    mac: ENC[AES256_GCM,data:5MGxvCOvseSorzp/otb70EsZxiVlZh0KNMYIzhSGHkItPEDaYqdGBCgDcCO9zjNzRdRwLbq4xO7dYmB6XvADvLuuyA9Tw4cKkTneu59GLL5Z5YjnDBJ9BKGEcE7kdpocEgKFB+G9BfDxlqtEWnMUAUtHdvYVZNQxt+gqTEDIWz8=,iv:OWOlArzu1X5NPxlwSWJlizBo5O/nP898OuGiazxc3+s=,tag:AGPnoc831IFrhylhhr/94w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
