apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:1ywKQb+UGvT3tdNNOLzlls1ACUzT9QlA8Ux1LdfUcLZXCxszfir5Xg==,iv:NAGsnQ8C5HOpuE7N46cBH9B5eiVBSBwm4LXZA84y9aA=,tag:u/BjLZV7XYSMYmkxP0YkCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZDZiVGVaK1NzWTBsOENq
            emxSV2ZOTzY1ZXMzVmQrbWZtZU0xNmdXNEFJCklLZUZIbktKUUhSb2VzS0Qwc25l
            NzNOaWdzcVh3MFcvdXVzZFZ2eTZXaW8KLS0tIEV3RVpEanVtay9wTmI5aS94c3cx
            TllWUjlaZkUwNHpkUERkT1pRUlRJSG8Kx1CW5XJcd8kP0p4WXXwjUVc6qFlGY/V0
            ZCUJIsqDB5jSnpc0iixE/Kt9o1lvyI6L+zzvZZjwmhFF7C9erNEvmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T03:56:38Z"
    mac: ENC[AES256_GCM,data:pYAEI7dFj8I6UyW4XL9gQ7qk6RoiCYENNmOqhYGUqyAMJhWMNYEmPzHaNS2mGvHi6sRZ9BusD/GquQeFXst0Y2vuBzoAnJmo5bkwvP8VUsf7s3SiMcx/+9/bx0AKMyHAk0uTA1OiDSrZbACzBjgT1wxwF3FDLtlG03N8fdgvKk8=,iv:SPDc+X1bhrcAPca1sFuUQly+i3CNj1w+8WfPx4y5/aY=,tag:/74aJ9ofMtvII01xPwFiJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Zg5+HuI1jMyEmRxBY9wmV/VLZhg=,iv:hJVoGMwLZJD0UhTlldNXMpfaY8lX2RUZHr0HBnMEEgs=,tag:xXLLZYBosyRUcFSEkV4nAw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JWT0rSGzKTR1S18oztpwnPBGJh268iJmSeBbTwfnEdGX0r8HEpgKpQ==,iv:GLuQYgHCCwyMkUowEVIpOa8Av58wHDzvqNdu1N6Sv24=,tag:Ra9CMF1meukG6SNbCEXr/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZDZiVGVaK1NzWTBsOENq
            emxSV2ZOTzY1ZXMzVmQrbWZtZU0xNmdXNEFJCklLZUZIbktKUUhSb2VzS0Qwc25l
            NzNOaWdzcVh3MFcvdXVzZFZ2eTZXaW8KLS0tIEV3RVpEanVtay9wTmI5aS94c3cx
            TllWUjlaZkUwNHpkUERkT1pRUlRJSG8Kx1CW5XJcd8kP0p4WXXwjUVc6qFlGY/V0
            ZCUJIsqDB5jSnpc0iixE/Kt9o1lvyI6L+zzvZZjwmhFF7C9erNEvmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T03:56:38Z"
    mac: ENC[AES256_GCM,data:pYAEI7dFj8I6UyW4XL9gQ7qk6RoiCYENNmOqhYGUqyAMJhWMNYEmPzHaNS2mGvHi6sRZ9BusD/GquQeFXst0Y2vuBzoAnJmo5bkwvP8VUsf7s3SiMcx/+9/bx0AKMyHAk0uTA1OiDSrZbACzBjgT1wxwF3FDLtlG03N8fdgvKk8=,iv:SPDc+X1bhrcAPca1sFuUQly+i3CNj1w+8WfPx4y5/aY=,tag:/74aJ9ofMtvII01xPwFiJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
