apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: kube-system
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:iHrnGzghhIgrl2qLAcUTCgfoySuRsC3CBTierBHQIlPFXaVCqG/Uxw==,iv:Ytpl4KJvlyoubXerFHisNb16yH8LPJJFEc+ZgclcClk=,tag:Ua0gfzJJrS+Ee23GAXtE/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaUdFMmJldlhISnVNYXhs
            VE5DaTJFRzZMSHFWMHJkUXBONTY5MDkxZ2dzCklNZ1lkN0pacVBYcmxvL3VmeDdV
            US9pbkp4Qlk4SkpnY2ZxL2JxZTdUaEEKLS0tIEhCWks4VnB4YTBBVHV4a2ttUE5M
            N3lRdlMrZnVqUU96OXNnQlJSN2VRbXMKMCP3EfoEB5rJG7KAfJ1SVKawC6QdtRUD
            P5Vm/yDzkDEFGQMgBizCYqNWdbGWxdmOKfHFxrP6xd8KDZ2OSpDybg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:04:40Z"
    mac: ENC[AES256_GCM,data:SGjU9zAF+NcWTvwzGrjMk5ckJWHauEWCWlyRnshtUOyPkO0X/9Q1+Ad6mxUEkFAQSlGX+uG7heUtQQGe0b35o/bYByKRGLnRq+N1eGz/8bhoZUM6ayeiqlk8blHoVs5lBjAgREE8ccwuj859LogGJaJ4nUmUeFF8qkVifB8dllA=,iv:6yi3emcsu7kSoePH3EnZeLUNaKCix0x3gsYHaZuWQE8=,tag:jwSREEPK3/4XC2YdQv22qA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:qmZlR6lHdHW9tsS5rHo9XTzJALU=,iv:FRcwE71E1tK9F3KRPDBBL3JNNz7bpjzpEBfu5c4WSN0=,tag:pPHoU7DS7bOjMqvPmxZ3oQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ORe/NFd/TTxgZpNp6QZjBf5NH2q+1ArNXAsHYbsuvQev3DTx3QkNyw==,iv:hsMW4ZEKmd+1HrXPUxG8mw6Vpbbk12XOQ9ROJx25FCI=,tag:8b2G190Yk9nmG528p3U9OQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h2p3ar9x8g6zchlmlaffq3yjk737y7ts0vc9x0mx6s9apwelg3csdsg22m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaUdFMmJldlhISnVNYXhs
            VE5DaTJFRzZMSHFWMHJkUXBONTY5MDkxZ2dzCklNZ1lkN0pacVBYcmxvL3VmeDdV
            US9pbkp4Qlk4SkpnY2ZxL2JxZTdUaEEKLS0tIEhCWks4VnB4YTBBVHV4a2ttUE5M
            N3lRdlMrZnVqUU96OXNnQlJSN2VRbXMKMCP3EfoEB5rJG7KAfJ1SVKawC6QdtRUD
            P5Vm/yDzkDEFGQMgBizCYqNWdbGWxdmOKfHFxrP6xd8KDZ2OSpDybg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T04:04:40Z"
    mac: ENC[AES256_GCM,data:SGjU9zAF+NcWTvwzGrjMk5ckJWHauEWCWlyRnshtUOyPkO0X/9Q1+Ad6mxUEkFAQSlGX+uG7heUtQQGe0b35o/bYByKRGLnRq+N1eGz/8bhoZUM6ayeiqlk8blHoVs5lBjAgREE8ccwuj859LogGJaJ4nUmUeFF8qkVifB8dllA=,iv:6yi3emcsu7kSoePH3EnZeLUNaKCix0x3gsYHaZuWQE8=,tag:jwSREEPK3/4XC2YdQv22qA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
